### ISSUE TITLE
Swarm Nest spawns take allied villages

### ISSUE THREAD

**Issue by momothefiddler** [elidupree/EoHS#129]

**Comment by elidupree** [comment]
Currently, the swarms are encouraged to take ANY non-own village by an equal amount. I am changing allied villages to be discouraged instead (although they will still step in allied villages if it gives them a good enough combat.)

**Comment by elidupree** [comment]
I made the discouragement big enough that they won't go to allied villages for healing, because the players probably care about their village arrangement more than the hitpoints of random swarm units.
