### ISSUE TITLE
Weapon specials and Soul Bind spell - unusual interactions

### ISSUE THREAD

**Issue by Ryrgwryr** [elidupree/EoHS#50]
<p><h2>Weapon specials and Soul Bind spell - unusual interactions</h2></p>
<ul>
<li>Chocobone is able to get drain weapon special on his charge attack through Soul Bind scroll, it didn't seem that overpowered however</li>
<li>Black Cat can't seem to be able to get weapon specials through Soul Bind scroll, tested with poison, drains and backstab</li>
<li>Soul Binding a unit with slows weapon special (granted by World Conquest II artifact) didn't seem to work and as discussed could be a seperate weapon special to avoid stacking with charge/drains/berserk</li>
</ul>

**Comment by elidupree** [comment]
The first 2 are definite bugs. I understand them and I can fix them.

The third MIGHT be a bug, but we don't know. One of us should test it by binding a custom unit that has melee slow normally, from some other era.

**Comment by Ryrgwryr** [comment]
Soul Bind casted on Ghazi from khalifate faction posessing both melee marksman and slow seems to work without any problems. This also shows that you can get two weapon specials from seperate attacks from Soul Bind without problems.
