### ISSUE TITLE
Don't use the real attack code for Pall of Fatigue?

### ISSUE THREAD

**Issue by elidupree** [elidupree/EoHS#73]
It's still pretty slow with large groups of enemies. Now that it can't kill, there's no particular reason for it to technically be an attack at all. Poison Ground, for instance, reduces enemy HP without being an attack.

Think this would affect:

* I would probably remove the chance to hit and just make it be guaranteed HP reduction. Maybe make the graphics more like Dark Pact, even.
* Mage Shield no longer blocks it (probably a flavor improvement)
* Your alignment doesn't affect it (bad)

I would still make it be cold damage (by modifying the HP reduction using wesnoth.unit_resistance, which includes abilities). And it would still be based on your attack strength, and be an "attack spell" that can be modified by battlemage. I could compute the damage using a single dummy attack against the dummy opponent, so that it would still automatically be modified by alignment, slow status, etc.

I might also slow down its progression like I did with fireball.

**Comment by momothefiddler** [comment]
Doesn't basing it off attack strength already take alignment into account? Or is it based on base attack strength in some way?

**Comment by elidupree** [comment]
Actually, the progression is already slower (currently at the center, the damage is 4 + attackstrength/10)
